"""empty message

Revision ID: 956b036bc38a
Revises: 
Create Date: 2022-06-03 03:29:48.802038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956b036bc38a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venues', sa.Boolean(), nullable=False))
    op.add_column('Artist', sa.Column('seeking_desc', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_desc')
    op.drop_column('Artist', 'seeking_venues')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
