"""Add seeking info venue model

Revision ID: 9d6f296fb7d8
Revises: e6a24c945600
Create Date: 2022-06-06 07:33:42.176151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6f296fb7d8'
down_revision = 'e6a24c945600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('Venue', sa.Column('seeking_desc', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_desc')
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
